### ISSUE TITLE
privateKey required, but may actually be privateKeyPem or privateKeyWif

### ISSUE THREAD

**Issue by cwebber** [w3c-ccg/ld-signatures#11]
From the signature spec text:

> The following algorithm specifies how to create a digital signature that can be later used to verify the authenticity and integrity of a linked data document. A linked data document, document, signature options, options, and a private key, privateKey, are required inputs.

However `privateKey` does not appear to be an input; instead `options` contains either `privateKeyPem` or `privateKeyWif` depending on the algorithm used.  I'm not sure how to rephrase this though to make it so that the private key field can be nicely specified by the algorithm without making the spec text clunky.

**Comment by dlongley** [comment]
And the language should really talk about a "signing function" or something like that rather than implying direct access to private key material as a requirement.

**Comment by msporny** [comment]
> However privateKey does not appear to be an input; instead options contains either privateKeyPem or privateKeyWif depending on the algorithm used.

It's important to note that the spec provides a lot of latitude to implementers on how the private key is specified in implementations. The spec doesn't say how you get the private key into the algorithm... just that the algorithm has access to it when it runs.

We certainly shouldn't specify that a PEM encoded private key is required... just that the private key material is accessible to the algorithm when it's running.

So that said, I don't see why we need to change the spec text... but I may be missing something.

**Comment by cwebber** [comment]
Again, I was misinterpreting `privateKey` as in terms of being a prescriptive argument name, my bad.  Same confusion as in #13.  However, there's a way in which this ties in: these names _do_ matter in that different signature suites may need different arguments (`privateKeyPem` vs `privateKeyWif` for instance) and that should be documented in the section describing that signature suite probably?  And the implementor needs to know _which_ of these arguments need to be part of the canonicalized options document (which I guess is all of them... I guess I'm conflating `options` as an argument in the reference implementation and `options` as in the [signature options](https://w3c-dvcg.github.io/ld-signatures/#dfn-signature-options) again, which has been the source of many of these issues).

I think the answer to that will again tie in with text changes from #13 so closing this.
