### ISSUE TITLE
A signature suite which skips the PEM/ASN.1 mess in favor of SPKI-style canonical s-exps

### ISSUE THREAD

**Issue by cwebber** [w3c-ccg/ld-signatures#15]
I suspect this issue will go nowhere, and that's okay ;)

But I know a number of people in the Linked Data Signatures world have tried to deal with the nightmare layer that lies underneath seemingly-innocuous PEM.  But there's a whole better structure out there that was attempted by SPKI (and even implemented by gnutls):

```
   The following is an RSA signature key, shown in advanced transport
   format:

   (public-key
    (rsa-pkcs1-md5
     (e #03#)
     (n
      |ANHCG85jXFGmicr3MGPj53FYYSY1aWAue6PKnpFErHhKMJa4HrK4WSKTO
      YTTlapRznnELD2D7lWd3Q8PD0lyi1NJpNzMkxQVHrrAnIQoczeOZuiz/yY
      VDzJ1DdiImixyb/Jyme3D0UiUXhd6VGAz0x0cgrKefKnmjy410Kro3uW1| )))
```

My gosh, so much easier to read!  And the canonical form is even easier to parse.  See 3.8.8.1 of this [SPKI document](http://theworld.com/~cme/spki.txt) and [the canonical s-expressions document](http://people.csail.mit.edu/rivest/Sexp.txt) to see how simple this is to structure and parse.

I'm sure I know the answer already, "we'd like to but everyone else is already using PEM", which is a fair argument.  Still, if we're writing an entirely new signatures system from scratch I can't resist suggesting that we fix one of the largest ills of the system.

Maybe the right route is to use PEM until everyone adopts Linked Data Signatures and then switch the system over to using `publicKeySexp`.  Well, I guess thanks to LDS' structure there's nothing stopping me from defining such a suite, but maybe I'd be the only one using it.

"I can't take you anywhere Chris" -- @msporny

**Comment by msporny** [comment]
I'm not disagreeing w/ most of what you said above, because you're right. Canonical s-expressions would be better. The problem is, security folks tend to get super upset when you change everything out from under them.

> if we're writing an entirely new signatures system from scratch

We're not doing that w/ LD Signatures... we're just packaging up stuff that already exists out there (PEM, RSA Signatures, etc.).

The reason we're using PEM-encoded stuff is exactly for the reason you mentioned... you can just stuff it into just about any library out there and it just works. It also ensures that the developers don't have to be exposed to the details... it's just a blob to them that they pass to a library, which means there is less stuff to screw up.

If you want to pursue this path, you will have to:

1. Convince everyone using PEM, ASN.1, etc. to switch away.
2. If you convince them to switch away, you'll have to convince them to not use JWK and use s-expressions instead.
3. If you convince them to use s-expressions, you'll have to go through years of security review on the thing you list above because it will be very new.
4. If you get through the security review, then you'll need to get that implemented across all the major languages before you see considerable uptake.

I'll be at the finish line cheering and congratulating you on an amazing accomplishment if you get through all 4 tasks above... see you in 10 years. :)

**Comment by msporny** [comment]
> Maybe the right route is to use PEM until everyone adopts Linked Data Signatures and then switch the system over to using publicKeySexp

Yes, this is the approach we're taking. You can list the encoding of your public keys in multiple formats now... publicKeyPem, publicKeyBase64, publicKeySexp, publicKeyJWK, etc. That's what we're depending on to avoid this quagmire of a debate.

**Comment by cwebber** [comment]
I agree it's a quagmire and I agree with everything you said above.  I guess in the future maybe I'll launch something using `publicKeySexp` and try to "lead the way", for all the success/disaster that may involve :)

Does that mean we can get `publicKeySexp` into the primary vocabulary? :)

**Comment by davidlehn** [comment]
Would the `publicKeySexp` value be a s-exp string?  Another option would be to use a vocab like https://www.w3.org/ns/auth/cert and avoid any custom parsing.  In either case, you'd likely have to build PEM data out of the data since that's what many libraries take as input.  Easier to just punt on the issue and use PEM.

**Comment by cwebber** [comment]
> Does that mean we can get publicKeySexp into the primary vocabulary? :)

Well, the right way to demonstrate vocabulary worth is to have actual usage, so on that note I think this issue can be closed since that doesn't exist at the second (though it might soon).

> Would the publicKeySexp value be a s-exp string?

Yes, in canonicalized form.

>  In either case, you'd likely have to build PEM data out of the data since that's what many libraries take as input. Easier to just punt on the issue and use PEM.

Often but not always.  libgcrypt, which is what I'm using for my Guile implementation of ActivityPub, uses canonical s-exps.  When I added http signatures support I was testing against the examples in the HTTP Signatures document and realized I had to convert the key over from PEM form... that's the path that lead me to realize what a nightmare PEM & friends is.  I initially figured I'd knock it out in a day but by the end of the day my head was melted like a pad of butter left out in the sun in summer in Phoenix Arizona.  After recovering from defeat, later that night I decided to compare by trying to write my own canonical s-exp parser... it only took me an hour or two and about 150 lines to write a simple recursive descent reader/writer, even in brain-melted-butter state.  So anyway, it's not always a foregone conclusion that PEM is the easier route to take either.  But yes, it is most widely deployed.  And it does mean that I'm "doomed" to sort out PEM parsing if I want to make progress in my Guile program (right now I'm shelling out to a Python script that extracts the info... not a production-safe path!)

Anyway, yeah choose your battles, and yes I'm probably not going to win this one.  I'm closing it, but for context [this post](https://twitter.com/ChristopherA/status/919957215104176130) is what made me think "gosh maybe we should try to set things on the right path".  Oh well... maybe some fresh and future project can make use of `publicKeySexp` and help set the world on the right path...
