### ISSUE TITLE
 canonicalized document for signature and verification. Why?

### ISSUE THREAD

**Issue by glauserr** [w3c-ccg/ld-signatures#24]
What does avoid to sign the json-ld document? Since to transfer to canonical for signing and verifying only adds additional complexity (and error resources for an application).

**Comment by Moopli** [comment]
JSON objects (in text representation) can be very different in terms of their exact text contents while being exactly the same in terms of parsing. For example, whitespace can be included (although usually it won't be), and JSON key ordering is not enforced (and it's very likely that different implementations will have different key orders unless they enforce a specific order), and either will completely change any hash result. Canonicalization is needed to ensure that a specific JSON object has exactly one canonical serialized representation, since the serialization is what is signed and verified.

**Comment by dmitrizagidulin** [comment]
@Moopli - thanks for answering the question!

@glauserr - If you have further questions, let us know, otherwise, this issue can be closed.

**Comment by nightpool** [comment]
I have a further question here—I understand the purpose of canonicalization, technically, but i'm not sure what use-case it serves. Why not sign and verify the JSON document at the byte level, without worrying about parsing? (and thus canonicalization). Can someone articulate an end-user facing use-case that wouldn't be served by just passing around the serialized document as-is, whitespace and all?

**Comment by nightpool** [comment]
There are problems beyond canonicalization that come with storing JSON-LD documents outside of their original serializations: see https://github.com/w3c-dvcg/ld-signatures/issues/7 for an example.

**Comment by dlongley** [comment]
@nightpool,

> Why not sign and verify the JSON document at the byte level, without worrying about parsing? (and thus canonicalization). Can someone articulate an end-user facing use-case that wouldn't be served by just passing around the serialized document as-is, whitespace and all?

There's significant implementation and storage burden with passing around (and saving) the serialized document. If you wanted to store the document in, for example, a document store, you'd have to store both the document and a serialized copy of it. Further difficulties are experienced if you want to use "set" signatures, whereby multiple parties sign the same document. This would require surgery on the serialized copy to append new signatures vs. using standard JSON parsing and serialization tools -- as they could modify the contents breaking the signature(s).

**Comment by dmitrizagidulin** [comment]
The two questions in this issue have been answered; closing. (If there are further questions, please feel free to open an issue on the https://github.com/w3c-ccg/ld-proofs/ repo).
