### ISSUE TITLE
LD Signatures and json-ld contexts which grow

### ISSUE THREAD

**Issue by cwebber** [w3c-ccg/ld-signatures#9]
(Like #7, this issue is maybe not an actual problem in the spec, but it is an issue that's being bumped into in practice and which having an answer for how to handle would be good.)

While removing terms is usually off the table, some json-ld contexts grow, and their vocabularies also grow.  Maybe one could argue that this should not happen, that vocabularies should be completely immutable, but I think that isn't realistic until the day people are accessing vocabularies in a more CAS / P2P way (more on that later).  For example, schema.org's context and vocabulary is regularly growing, and so is ActivityStreams (thus ActivityPub's users face this).

Compounding this problem is that users generally want to avoid having to rely on the uptime of a context's server and avoid DDOS'ing it too.  Thus, these servers may bundle a context with their application as a "good practice".  But what happens when such a vocabulary changes?

For example, Mastodon is now rolling out ActivityPub + Linked Data Signatures support.  In order to avoid the above issues they include the context at build time.  Right now we're also evaluating adding some "extensions" to the ActivityStreams vocabulary (which the Social Community Group is authorized to do) such as a `sensitive` boolean (equivalent to `nsfw` in some places).  This is fine for now because this is the first time this is rolled out, but what happens if we have an extension in the future?

As a very silly hypothetical example, say we add a new `karma` property that links to some social "karma currency".  Users can give "karma" to each other, and links to the karma-id of a post are attached to an object, from which a user can look up the karma value.  Users like the feature and we add it to an ActivityStreams extension and it gets added to the context.  A new version of Mastodon rolls out with karma support, and those objects are of course signed with LDS.  But there's a problem: older versions of Mastodon don't have the `karma` property in their cached context, and so when the normalization process is done those terms get dropped, and thus the nodes running an older verison of Mastodon see those signatures as failing.

Possible answers to this:
- "Don't add new terms to a context!"  Well, this isn't happening in practice, and almost certainly will not happen to schema.org (which is probably the most popular json-ld context on earth?) .  This can be achieved by either:
  - versioning contexts (which adds the pain of tracking versions)
  - composing together a new context with every new extension added (your context list could grow really long and this could be very annoying to programmers)
- Content Addressed Storage and a peer to peer delivery mechanism for contexts will provide the opportunity for contexts to grow and allow lookup without DDOS'ing any particular node!  Okay, true, but that's a glorious future that's not here yet and we can't propose it in seriousness to users yet. ;)
- Have users bundle a context as a fallback, but also occasionally try to fetch and cache the latest version of a context and re-fetch based on cache-control headers.  Could be done but effectively adds an asynchronous cronjob interface to your system; some types of programs may not even have a nice way to do this (ie request-response-only PHP applications)
- For several releases after a "new term" is added, manually add that term to the context to give older nodes a chance to "catch up", like so:
```
{"@context": ["https://www.w3.org/ns/activitystreams",
              {"karma": "as:karma"}]}
```

Other suggestions or solutions?

**Comment by cwebber** [comment]
One other "solution" would be to use LDS as the structure to hold the signature but use a not-very-linked-data signature algorithm that just sorts json keys and writes them in a consistent way for signatures.  Not very compelling from a linked data standpoint, but it would survive this issue better.

**Comment by dlongley** [comment]
@cwebber,

> One other "solution" would be to use LDS as the structure to hold the signature but use a not-very-linked-data signature algorithm that just sorts json keys and writes them in a consistent way for signatures. Not very compelling from a linked data standpoint, but it would survive this issue better.

Then you lose the semantics of what you're signing -- and you therefore introduce a new problem. Namely:

A: "Hey, you promised to pay me 5 karmas! I have the signature right here."

B: "No, I promised to pay you 5 karmas, not 5 karmas!"

There's a good reason to make sure that there's a vocabulary backing what you're signing in a very decentralized world.

**Comment by cwebber** [comment]
@dlongley Yeah, I agree that route has those problems, I'm not wild about it.  But the fact that LDS *can* in theory be used as a structure for representing that has come up as a suggestion for this.  Good to capture why that introduces a new problem :)

**Comment by msporny** [comment]
@cwebber you've basically covered all of the options. 

The short advice to developers is: make sure all of your properties are in the context when you sign or you're in for a world of pain. We're going to be adding a feature to the reference implementation library to throw an error when you're signing and terms are dropped.

> "Don't add new terms to a context!" 

Yeah, this doesn't work. Not a solution.

> versioning contexts (which adds the pain of tracking versions)

Do this and then don't remove terms. Adding terms is fine. Developers that add their own terms and digitally sign them, counting on the context from not adding conflicting terms in the future, are in for a world of pain. This needs to be more clearly spelled out for developers. What you digitally sign matters and signatures should break easily (if they don't, people can change things w/o a security repercussion, which is terrible security design).

> composing together a new context with every new extension added (your context list could grow really long and this could be very annoying to programmers)

Don't do this, too difficult.

> Content Addressed Storage and a peer to peer delivery mechanism for contexts will provide the opportunity for contexts to grow and allow lookup without DDOS'ing any particular node! Okay, true, but that's a glorious future that's not here yet and we can't propose it in seriousness to users yet. ;)

This is exactly what we're planning to do once our Veres Ledger stuff goes into production. There will be a decentralized ledger specifically tuned for versioned JSON-LD contexts. The only downside here is that you need to put the content-addressible hash in the @context and that's not very human readable. We have some ideas around making it human readable, though.

> Have users bundle a context as a fallback, but also occasionally try to fetch and cache the latest version of a context and re-fetch based on cache-control headers. 

Yes, this is also possible but tends to be fragile for the "dropped property" use case you mention before.

There are two other options, which is to make your system cache every single context it fetches and to use the context appropriate to the timestamp of the message. The problem here is implementer burden, and I expect most implementers to be lazy and not implement this.

The other option is to freeze major versions of contexts... so v1, v2, v3... this is what we do w/ many of our contexts like: https://w3id.org/security/v1 and we only freeze that when a WG adopts it. Then we quickly switch to https://w3id.org/security/v2 and tell all implementers to use that for all new development and to ONLY deploy v2 into production when the WG is done w/ it.

I don't think either of those two approaches will scale, which means that the real long-term solution is the content-addressable cryptographic ledger approach, which we're closer to deploying than you thought previously. Once that ledger goes live, we may build something into the signature libraries that automatically register and replace the @context w/ a content-addressable one when performing a digital signature. That is easy on developers 

The short term "fix" is to:

1) Make the Linked Data Signature libraries throw if a property is dropped during signing.
2) Version JSON-LD Contexts.
3) Ship necessary JSON-LD contexts w/ software.

Thoughts, @cwebber?

**Comment by cwebber** [comment]
Thanks for the detailed reply, @msporny!  I think I agree with everything you wrote.  It's good to see that we're in alignment with CAS being the long-term solution but needing to deal with things in the short term.  So as to your suggestions for the short term:

> 1. Make the Linked Data Signature libraries throw if a property is dropped during signing.
> 2. Version JSON-LD Contexts.
> 3. Ship necessary JSON-LD contexts w/ software.

That does sound like the right solution to me, and for implementations going forward I think we should recommend it.

For my own use case, I'm afraid the chance to get ActivityStreams' context versioned has passed.  Luckily I do not anticipate the AS2 core vocabulary changing.  Perhaps the right thing to do is to not try to add extensions to ActivityStreams' context, but rather build an ActivityPub context which *is* versioned and includes the AS2 core context.  However, that could be its own challenge, and I suppose is not all to relevant to LDS itself.

Since we are talking about making LDS throw an error for properties that can't be found in the context (which is the right thing to do IMO for security reasons) we should be sure that current implementors are aware that change is coming; specifically I think @gargron should be aware since I think this affects Mastodon's implementation decisions.

**Comment by cwebber** [comment]
`https://www.w3.org/ns/activitystreams/` is likely to keep mutating in append-only fashion, and maybe this is just fine, since that doesn't preclude having a versioned one as well that's more specific.

One thing we discussed in #social is that maybe instead of incrementally increasing the version of the context like `https://www.w3.org/ns/activitystreams/v1.3` we could add a small amount of content addressing and instead put the hash itself in there like `https://www.w3.org/ns/activitystreams/8b8e384b31fef5b62e3a5ff6e408a8f7358cf1b4ce562da82baaca479e3b48aa`.

**Comment by sandhawke** [comment]
I've now implemented this so people can experiment:

https://www.w3.org/ns/activitystreams-history/

contains all (eight so far) versions of the jsonld version of the namespace document, with cache control max-age 1 year.

It's generated by a shell script at https://github.com/sandhawke/expose-history .   There are numbered and hashed versions, since I'm not sure which people will prefer.

The idea here is instead of using @context="https://www.w3.org/ns/activitystreams" as one SHOULD as per https://www.w3.org/TR/activitystreams-core/#jsonld, if one is using LDS, one instead should use one of these frozen versions of the context.  That way we avoid sender and receiver potentially using a different version of the context, while still allowing caching (and in fact a lot more caching).

Hoping this works...

**Comment by msporny** [comment]
@sandhawke I think the solution you created is going to be fine for the foreseeable future.

**Comment by cwebber** [comment]
Horray!
I guess now my question would be, where would we want to put advice on this?  Should we put it in the document in some sort of non-normative best practices section?  I'm not quite sure it's "security considerations".

**Comment by msporny** [comment]
> I guess now my question would be, where would we want to put advice on this? Should we put it in the document in some sort of non-normative best practices section?

There has been talk (for years now) about creating a JSON-LD Best Practices document... this sort of belongs there. I think @gkellogg might have been thinking about something along these lines, but I can't remember if it was him or someone else that was drawing those up.

**Comment by cwebber** [comment]
Cool... well in any case, it sounds like it doesn't belong on Linked Data Signatures spectext itself, so I'm happy closing this ticket.  If such a document gets started I'd be happy to contribute to the language around this on it.

**Comment by sandhawke** [comment]
As I'm understanding it, this technique (or an equivalent) is required in order to use LDS in practice without error.   As such, it seems like it ought to be described in informative text in the LDS spec.

**Comment by cwebber** [comment]
Well, I'll reopen it then and let the spec editors decide if that's the case. :)

If we do want to take a shot at putting some text in the spec itself I could give it a try.

**Comment by gkellogg** [comment]
I had, in fact, done work on the best practices document. At this point, I think it comes down to finding needs for such practices, or new areas of such practices themselves.

**Comment by sandhawke** [comment]
Hi Gregg, did your planned BP include this bit -- having people using immutable-content URLs for their contexts? If not, did you have some other design that would eg allow Mastodon to use LDS?   Like, how can anyone use LDS without it, assuming real-world features like different systems be running different versions of the code, and the schema changes over time.

**Comment by gkellogg** [comment]
Hi Sandro, I agree that such a BP is needed, but we n the d a solution to emerge that JSON-LD can adopt. In addition to payments, WoT really needs this functionality. It seems like a web-infrastuctute, and not just a JSON-LD or LDS concern.

**Comment by msporny** [comment]
> As I'm understanding it, this technique (or an equivalent) is required in order to use LDS in practice without error. As such, it seems like it ought to be described in informative text in the LDS spec.

Ok, I'll try to craft some text during the next edit cycle to capture this so that we can warn developers of this pitfall. Also, I'm currently simultaneously editing no less than 10 different specs so the edit cycles are realllly long. Happy to accept a PR if anyone crafts one before I get around to it. :)

**Comment by dmitrizagidulin** [comment]
This is an important discussion (that has to do with how to version JSON-LD contexts). However, it's out of scope of this particular spec (and applies to all json-ld specs). 
For what it's worth, the current discussion can be followed over at https://github.com/w3c/did-core/issues/5

Closing this issue, though.
